apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-self-healer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-self-healer
  template:
    metadata:
      labels:
        app: k8s-self-healer
    spec:
      containers:
        - name: controller
          image: k8s-self-healer:latest
          ports:
            - containerPort: 8080
