apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-self-healer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch", "patch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-self-healer-binding
subjects:
  - kind: ServiceAccount
    name: k8s-self-healer
    namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-self-healer-role
  apiGroup: rbac.authorization.k8s.io
